changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: 新增功能
      labels:
        - feature
        - enhancement
    - title: 问题修复
      labels:
        - bug
        - fix
    - title: 文档更新
      labels:
        - documentation
        - docs
    - title: 维护调整
      labels:
        - dependencies
        - refactor
        - chore
    - title: 其他更新
      labels:
        - "*"
